# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 19:23
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171007_0150'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username'], name='users_user_usernam_dff516_gin'),
        ),
    ]
