# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', fields.MaxCharField(help_text='Не более 255 символов<br/>Не более 255 символов', max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', fields.MaxCharField(help_text='Не более 255 символов<br/>Не более 255 символов', max_length=255, verbose_name='Title')),
                ('body', fields.MaxCharField(help_text='Не более 255 символов<br/>Не более 255 символов', max_length=255, verbose_name='Body')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='Case')),
            ],
        ),
    ]
