# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20170920_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='image',
            field=models.ImageField(default='eeee.jpg', upload_to='', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=fields.MaxCharField(help_text='Не более 255 символов<br/>Не более 255 символов<br/>Не более 255 символов', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=fields.MaxCharField(help_text='Не более 255 символов<br/>Не более 255 символов<br/>Не более 255 символов', max_length=255, verbose_name='Title'),
        ),
    ]
