# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 21:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0005_auto_20170924_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'User-Stage',
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=fields.MaxCharField(help_text='Не более 255 символов<br/>Не более 255 символов<br/>Не более 255 символов', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=fields.MaxCharField(help_text='Не более 255 символов<br/>Не более 255 символов<br/>Не более 255 символов', max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='userstage',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
        migrations.AddField(
            model_name='userstage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Stage'),
        ),
        migrations.AddField(
            model_name='userstage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stage',
            name='users',
            field=models.ManyToManyField(through='cases.UserStage', to=settings.AUTH_USER_MODEL, verbose_name='Users on that stage'),
        ),
        migrations.AlterUniqueTogether(
            name='userstage',
            unique_together=set([('user', 'case')]),
        ),
    ]
