# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 01:50
from __future__ import unicode_literals

from django.db import migrations
import fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20171006_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='title',
            field=fields.MaxCharField(help_text='Не более 255 символов<br/>Не более 255 символов<br/>Не более 255 символов', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=fields.MaxCharField(help_text='Не более 255 символов<br/>Не более 255 символов<br/>Не более 255 символов', max_length=255, verbose_name='Title'),
        ),
    ]
