# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 19:23
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations
import fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20171007_0150'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=fields.MaxCharField(help_text='Не более 255 символов<br/>Не более 255 символов<br/>Не более 255 символов', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=fields.MaxCharField(help_text='Не более 255 символов<br/>Не более 255 символов<br/>Не более 255 символов', max_length=255, verbose_name='Title'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='cases_case_title_81b6f9_gin'),
        ),
    ]
