# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20171010_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=fields.MaxCharField(help_text='Не более 255 символов<br/>Не более 255 символов<br/>Не более 255 символов', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=fields.MaxCharField(help_text='Не более 255 символов<br/>Не более 255 символов<br/>Не более 255 символов', max_length=255, verbose_name='Title'),
        ),
    ]
